SCALE_TYPES = ["maj", "min"]
SCALES = {
    "maj": {
        "C": ["C", "D", "E", "F", "G", "A", "B", "C"],
        "G": ["G", "A", "B", "C", "D", "E", "F#", "G"],
        "D": ["D", "E", "F#", "G", "A", "B", "C#", "D"],
        "A": ["A", "B", "C#", "D", "E", "F#", "G#", "A"],
        "E": ["E", "F#", "G#", "A", "B", "C#", "D#", "E"],
        "B": ["B", "C#", "D#", "E", "F#", "G#", "A#", "B"],
        "F#": ["F#", "G#", "A#", "B", "C#", "D#", "E#", "F#"],
        "C#": ["C#", "D#", "E#", "F#", "G#", "A#", "B#", "C#"],
        "F": ["F", "G", "A", "Bb", "C", "D", "E", "F"],
        "Bb": ["Bb", "C", "D", "Eb", "F", "G", "A", "Bb"],
        "Eb": ["Eb", "F", "G", "Ab", "Bb", "C", "D", "Eb"],
        "Ab": ["Ab", "Bb", "C", "Db", "Eb", "F", "G", "Ab"],
        "Db": ["Db", "Eb", "F", "Gb", "Ab", "Bb", "C", "Db"],
        "Gb": ["Gb", "Ab", "Bb", "Cb", "Db", "Eb", "F", "Gb"],
        "Cb": ["Cb", "Db", "Eb", "Fb", "Gb", "Ab", "Bb", "Cb"],
    },
    "min": {
        "A": ["A", "B", "C", "D", "E", "F", "G", "A"],
        "E": ["E", "F#", "G", "A", "B", "C", "D", "E"],
        "B": ["B", "C#", "D", "E", "F#", "G", "A", "B"],
        "F#": ["F#", "G#", "A", "B", "C#", "D", "E", "F#"],
        "C#": ["C#", "D#", "E", "F#", "G#", "A", "B", "C#"],
        "G#": ["G#", "A#", "B", "C#", "D#", "E", "F#", "G#"],
        "D#": ["D#", "E#", "F#", "G#", "A#", "B", "C#", "D#"],
        "A#": ["A#", "B#", "C#", "D#", "E#", "F#", "G#", "A#"],
        "D": ["D", "E", "F", "G", "A", "Bb", "C", "D"],
        "G": ["G", "A", "Bb", "C", "D", "Eb", "F", "G"],
        "C": ["C", "D", "Eb", "F", "G", "Ab", "Bb", "C"],
        "F": ["F", "G", "Ab", "Bb", "C", "Db", "Eb", "F"],
        "Bb": ["Bb", "C", "Db", "Eb", "F", "Gb", "Ab", "Bb"],
        "Eb": ["Eb", "F", "Gb", "Ab", "Bb", "Cb", "Db", "Eb"],
        "Ab": ["Ab", "Bb", "Cb", "Db", "Eb", "Fb", "Gb", "Ab"],
    },
}


SHARPS = {
    "A": "A#",
    "Ab": "A",
    "A#": "B",
    "B": "C",
    "Bb": "B",
    "B#": "C#",
    "C": "C#",
    "Cb": "C",
    "C#": "D",
    "D": "D#",
    "Db": "D",
    "D#": "E",
    "E": "F",
    "Eb": "E",
    "E#": "F#",
    "F": "F#",
    "Fb": "F",
    "F#": "G",
    "G": "G#",
    "Gb": "G",
    "G#": "A",
}

FLATS = {
    "A": "G#",
    "Ab": "G",
    "A#": "A",
    "B": "A#",
    "Bb": "A",
    "B#": "B",
    "C": "B",
    "Cb": "Bb",
    "C#": "C",
    "D": "C#",
    "Db": "C",
    "D#": "D",
    "E": "D#",
    "Eb": "D",
    "E#": "E",
    "F": "E",
    "Fb": "D#",
    "F#": "F",
    "G": "F#",
    "Gb": "F",
    "G#": "G",
}


CHORD_TYPES = ["maj", "min", "dim", "aug", "maj7", "m7", "7"]

INTERVALS_BY_CHORD_TYPE = {
    "maj": ["root", "major third", "perfect fifth"],
    "min": ["root", "minor third", "perfect fifth"],
    "dim": ["root", "minor third", "diminished fifth"],
    "aug": ["root", "major third", "augmented fifth"],
    "maj7": ["root", "major third", "perfect fifth", "major seventh"],
    "m7": ["root", "minor third", "perfect fifth", "minor seventh"],
    "7": ["root", "major third", "perfect fifth", "minor seventh"],
}
